feat: add GerritKit and plugins
gerritkit/client pull request #1
Opened 2020-09-07 15:28 UTC by pismenskiy

2020-09-08 05:55 UTC, antongolub requested changes

2020-09-08 05:55 UTC, antongolub commented on packages/rest/package.json
>    },
Move to package/infra

2020-09-08 05:55 UTC, antongolub commented on packages/infra/tsconfig.compiler.json
> +    "lib": ["esnext", "DOM"],
DOM?

2020-09-24 11:48 UTC, antongolub requested changes

2020-09-24 11:48 UTC, antongolub commented on packages/generator/README.md
> +# @gerritkit/rest
generator

2020-09-24 11:48 UTC, antongolub commented on packages/generator/package.json
> +  "version": "1.0.0",
0.0.0

2020-09-24 11:48 UTC, antongolub commented on packages/generator/package.json
> +  "description": "Generator rest api",
Code generator for gerrit REST API

2020-09-24 11:48 UTC, antongolub commented on packages/generator/package.json
> +    "build:libdef": "dts-generator --project ./ --out typings/index.d.ts --prefix @gerritkit/rest/target/es5 --name @gerritkit/rest --main @gerritkit/rest/target/es5/index && libdeffix --dts=./typing
libdefkit 2.0

2020-09-24 11:48 UTC, antongolub commented on packages/generator/package.json
> +    "@types/cheerio": "^0.22.21"
prod dep

2020-09-24 11:48 UTC, antongolub commented on packages/generator/src/main/ts/index.ts
> +  ${dataType}
missed tab?

2020-09-24 11:48 UTC, antongolub commented on packages/generator/src/test/ts/index.ts
> +const api =
apiDocsUrl

2020-09-24 11:48 UTC, antongolub commented on packages/generator/src/test/ts/index.ts
> +const api =
Or
const gerritUrl = '...'
const gerritDocsUrl = `${gerritUrl}/Documentation/rest-api-projects.html`

2020-09-24 11:48 UTC, antongolub commented on packages/rest/src/main/ts/api/access.ts
> +const parseGerritResponse = (data: { data: string }) =>
.slice('some prefix'.length)

2020-09-24 11:48 UTC, antongolub commented on packages/rest/src/main/ts/api/config.ts
> +  JSON.parse(data.data.slice(4))
What's there? If smth like '  ' you may use `.trim()` instead of slice

2020-09-24 11:48 UTC, antongolub commented on packages/rest/src/main/ts/types.ts
> +export type Constructor<T> = new (...args: any[]) => T
@substrate

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +  isUnsupported: boolean
unused property

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +  const pathArgsType =
use extract function

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +        ${opts.map(([name, filed]) => `${filed}: ${name}`).join(',\n')}
use extract function

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +export function normaliseName(name: string) {
check name.length

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +export function parseArg(arg: string) {
check arg.length

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +  }, {} as Record<any, any>)
rewrite counter to util func

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +    })
can you unify this?

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +      )
use extract function

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +      ;(el.match(/\S+?\s(?=entries)/g) || []).forEach((type) =>
use extract function like above and then unify (maybe)

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +const unsupported = []
unused

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +  const methods: any[] = []
any?

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +  $('div.sect2').each((_i, elem) => methods.push(getMethodInfo(elem)))
_index, element

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +  const methods: any[] = []
add typings for getMethodInfo and use here

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +    .each((_, elem) => {
_index, element

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +  const data: any = []
const data: string = []

2020-09-24 19:39 UTC, bre30kra69cs commented on packages/generator/src/main/ts/index.ts
> +  const result: any[] = []
add typings for getTypesInfo and use here

2020-09-28 13:11 UTC, antongolub approved these changes

2020-09-28 13:13 UTC, merged

2020-09-28 13:30 UTC, antongolub commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@gerritkit/generator/v/1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-09-28 13:30 UTC, antongolub commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@gerritkit/core/v/1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-09-28 13:30 UTC, antongolub commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@gerritkit/infra/v/1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-09-28 13:30 UTC, antongolub commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@gerritkit/rest/v/1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-10-08 11:24 UTC, antongolub commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@gerritkit/native/v/1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: